import fs from "node:fs";
import path from "node:path";
import { canonicalUrl, CONTACT_FORM_ENDPOINT, DEFAULT_LOCALE, DISCORD_GUILD_ID, DISCORD_INVITE_URL, DOWNLOAD_URLS, localePath, LOCALES, PAGES, SITE_NAME, SITE_URL, TURNSTILE_SITE_KEY } from "./site-config.mjs";

const ROOT=process.cwd();
const read=(file)=>fs.readFileSync(path.join(ROOT,file),"utf8").replace(/^\uFEFF/,"");
const write=(file,content)=>{const target=path.join(ROOT,file);fs.mkdirSync(path.dirname(target),{recursive:true});fs.writeFileSync(target,content,"utf8");};
const escapeHtml=(value)=>String(value??"").replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");
const jsonLd=(value)=>JSON.stringify(value).replace(/</g,"\\u003c");

function parseCsv(content){const rows=[];let row=[],cell="",quoted=false;for(let i=0;i<content.length;i+=1){const c=content[i],next=content[i+1];if(c==='"'){if(quoted&&next==='"'){cell+='"';i+=1;}else quoted=!quoted;continue;}if(c===","&&!quoted){row.push(cell);cell="";continue;}if((c==="\n"||c==="\r")&&!quoted){if(c==="\r"&&next==="\n")i+=1;row.push(cell);if(row.length>1||row[0]!=="")rows.push(row);row=[];cell="";continue;}cell+=c;}if(cell.length||row.length){row.push(cell);rows.push(row);}const headers=rows.shift()??[];return rows.map(values=>Object.fromEntries(headers.map((header,index)=>[header,(values[index]??"").trim()])));}
const strings=new Map();for(const row of parseCsv(read("i18n/strings-site.csv"))){if(!row.key)throw new Error("Translation row missing key");if(strings.has(row.key))throw new Error(`Duplicate translation key: ${row.key}`);strings.set(row.key,row);}
function t(key,locale){const row=strings.get(key);if(!row)throw new Error(`Missing translation key: ${key}`);const value=row[locale]||row[DEFAULT_LOCALE];if(!value)throw new Error(`Missing translation value: ${key}`);return value;}
function render(template,replacements){let result=template;for(const [key,value] of Object.entries(replacements))result=result.split(`{{${key}}}`).join(String(value));return result;}
function renderBody(source,locale){return read(`templates/pages/${source}.html`).replace(/{{t:([a-z0-9._-]+)}}/gi,(_m,key)=>escapeHtml(t(key,locale))).replace(/data-build-route="([a-z0-9/_-]+)" href="#"/gi,(_m,route)=>`href="${localePath(locale,route)}"`).replace(/data-build-contact href="#"/gi,`href="${localePath(locale)}index.html#contact"`).replace(/data-build-download="([a-z0-9_]+)" href="#"/gi,(_m,key)=>{const url=DOWNLOAD_URLS[key];if(!url)throw new Error(`Missing download URL: ${key}`);return `href="${escapeHtml(url)}"`;}).replace(/data-build-discord-invite href="#"/gi,`href="${escapeHtml(DISCORD_INVITE_URL)}"`).replace(/data-build-discord-widget class=/gi,`data-discord-guild="${escapeHtml(DISCORD_GUILD_ID)}" class=`).replace(/src="about:blank"/gi,`src="https://discord.com/widget?id=${escapeHtml(DISCORD_GUILD_ID)}&amp;theme=light"`).replace(/data-build-contact-form action="#"/gi,`action="${escapeHtml(CONTACT_FORM_ENDPOINT)}"`).replace(/data-build-locale value="en"/gi,`value="${escapeHtml(locale)}"`).replace(/data-build-turnstile data-sitekey=""/gi,`data-sitekey="${escapeHtml(TURNSTILE_SITE_KEY)}"`).replace(/{{url:([a-z0-9/_-]+)}}/gi,(_m,route)=>localePath(locale,route==="home"?"":route)).replace(/{{download:([a-z0-9_]+)}}/gi,(_m,key)=>{const url=DOWNLOAD_URLS[key];if(!url)throw new Error(`Missing download URL: ${key}`);return escapeHtml(url);});}
function hreflangs(route){const links=Object.entries(LOCALES).map(([locale,settings])=>`<link rel="alternate" hreflang="${settings.hreflang}" href="${canonicalUrl(locale,route)}">`);links.push(`<link rel="alternate" hreflang="x-default" href="${canonicalUrl(DEFAULT_LOCALE,route)}">`);return links.join("\n  ");}
function languageLinks(current,route){return Object.entries(LOCALES).map(([locale,settings])=>`<li><a href="${localePath(locale,route)}" hreflang="${settings.hreflang}"${locale===current?' aria-current="page"':""}>${escapeHtml(settings.nativeName)}</a></li>`).join("\n");}
function redirect(route=""){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><meta http-equiv="refresh" content="0;url=${localePath(DEFAULT_LOCALE,route)}"><title>Redirecting | ${SITE_NAME}</title><link rel="canonical" href="${canonicalUrl(DEFAULT_LOCALE,route)}"></head><body><p>Redirecting to <a href="${localePath(DEFAULT_LOCALE,route)}">${localePath(DEFAULT_LOCALE,route)}</a>...</p></body></html>`;}

const shell=read("templates/site.tpl");
for(const locale of Object.keys(LOCALES)){for(const page of PAGES){const title=t(page.titleKey,locale),description=t(page.descriptionKey,locale);const html=render(shell,{HTML_LANG:LOCALES[locale].htmlLang,PAGE_TITLE:escapeHtml(title),PAGE_DESCRIPTION:escapeHtml(description),ROBOTS:page.robots||"index,follow,max-image-preview:large",SITE_NAME:escapeHtml(t("site.name",locale)),SITE_TAGLINE:escapeHtml(t("site.tagline",locale)),OG_LOCALE:LOCALES[locale].ogLocale,CANONICAL_URL:canonicalUrl(locale,page.route),HREFLANG_LINKS:hreflangs(page.route),HEAD_EXTRAS:page.source==="home"?'<script src="https://challenges.cloudflare.com/turnstile/v0/api.js?render=explicit&onload=onTurnstileLoad" async defer></script>':"",ORG_JSON_LD:jsonLd({"@context":"https://schema.org","@type":"Organization",name:SITE_NAME,url:SITE_URL,sameAs:[DISCORD_INVITE_URL]}),WEBPAGE_JSON_LD:jsonLd({"@context":"https://schema.org","@type":"WebPage",name:title,description,url:canonicalUrl(locale,page.route),inLanguage:LOCALES[locale].htmlLang}),BODY_CLASS:page.bodyClass,PAGE_BODY:renderBody(page.source,locale),HOME_URL:localePath(locale),BLACKBIRD_URL:localePath(locale,"products/blackbird"),PRODUCTS_URL:localePath(locale,"products"),SERVICES_URL:localePath(locale,"services"),ABOUT_URL:localePath(locale,"about"),SHOP_URL:localePath(locale,"shop"),PRIVACY_URL:localePath(locale,"privacy"),EULA_URL:localePath(locale,"eula"),CONTACT_URL:`${localePath(locale)}index.html#contact`,NAV_BLACKBIRD:escapeHtml(t("nav.blackbird",locale)),NAV_PRODUCTS:escapeHtml(t("nav.products",locale)),NAV_SERVICES:escapeHtml(t("nav.services",locale)),NAV_ABOUT:escapeHtml(t("nav.about",locale)),NAV_SHOP:escapeHtml(t("nav.shop",locale)),NAV_CONTACT:escapeHtml(t("nav.contact",locale)),NAV_PRIVACY:escapeHtml(t("nav.privacy",locale)),NAV_EULA:escapeHtml(t("nav.eula",locale)),NAV_MENU:escapeHtml(t("nav.menu",locale)),NAV_LANGUAGE:escapeHtml(t("nav.language",locale)),LANGUAGE_LINKS:languageLinks(locale,page.route),THEME_TO_LIGHT:escapeHtml(t("theme.to_light",locale)),THEME_TO_DARK:escapeHtml(t("theme.to_dark",locale)),FOOTER_STATUS:escapeHtml(t("footer.status",locale)),FOOTER_RIGHTS:escapeHtml(t("footer.rights",locale))});write(`${locale}/${page.route?`${page.route}/`:""}index.html`,html);}}
write("index.html",redirect());for(const page of PAGES.filter(page=>page.route))write(`${page.route}/index.html`,redirect(page.route));
write("404.html",`<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,follow"><meta name="color-scheme" content="light dark"><script>try{const theme=localStorage.getItem("incogent_theme");if(theme==="dark"||theme==="light")document.documentElement.setAttribute("data-theme",theme);}catch(_error){}</script><title>Page not found | ${SITE_NAME}</title><link rel="stylesheet" href="/site.css?v=20260806-contact"></head><body><main class="section"><div class="wrap narrow"><p class="eyebrow">404</p><h1>Page not found</h1><p>The requested page could not be found.</p><a class="button primary" href="/en/">Return home</a></div></main></body></html>`);
const urls=[];for(const locale of Object.keys(LOCALES))for(const page of PAGES)if(page.includeInSitemap!==false)urls.push(canonicalUrl(locale,page.route));write("sitemap.xml",`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.map(url=>`  <url><loc>${url}</loc></url>`).join("\n")}\n</urlset>\n`);write("robots.txt",`User-agent: *\nAllow: /\n\nSitemap: ${SITE_URL}/sitemap.xml\n`);console.log(`Generated ${PAGES.length} page(s) for: ${Object.keys(LOCALES).join(", ")}`);
