import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { renderPolicy } from './render-policy.mjs';
const source = readFileSync('privacy/Incogent_Privacy_Policy.md', 'utf8');
const rendered = renderPolicy(source);
const page = readFileSync('en/privacy/index.html', 'utf8');
assert.ok(page.includes(rendered));
assert.equal((rendered.match(/<h2 /g) || []).length, 18);
assert.ok(rendered.includes('mailto:legal@incogent.io'));
assert.ok(rendered.includes('directly to Discord'));
assert.ok(rendered.includes('within 90 days'));
assert.ok(rendered.includes('review unresolved reports quarterly'));
assert.ok(!/REVIEW DRAFT|Publication review item|Policy drafting required|{{/.test(page));
assert.throws(() => renderPolicy('# Incogent Privacy Policy\n\nREVIEW DRAFT'));
assert.ok(renderPolicy('# Incogent Privacy Policy\n\n<script>alert(1)</script>').includes('&lt;script&gt;'));
console.log('Policy source/rendering and publication guards passed.');

const links = renderPolicy('# Incogent Privacy Policy\n\n<https://www.incogent.io/privacy> **legal@incogent.io** https://example.com/path. [Existing](https://example.com/?a=1&b=2)');
assert.ok(links.includes('<a href="https://www.incogent.io/privacy">https://www.incogent.io/privacy</a>'));
assert.ok(links.includes('<strong><a href="mailto:legal@incogent.io">legal@incogent.io</a></strong>'));
assert.ok(links.includes('<a href="https://example.com/path">https://example.com/path</a>.'));
assert.ok(links.includes('<a href="https://example.com/?a=1&amp;b=2">Existing</a>'));
assert.equal((links.match(/<a /g) || []).length, 4);
const eulaSource = readFileSync('eula/Blackbird_EULA.md', 'utf8');
const eulaRendered = renderPolicy(eulaSource, '# Blackbird End User License Agreement');
assert.ok(readFileSync('en/eula/index.html', 'utf8').includes(eulaRendered));
assert.ok(eulaRendered.includes('href="https://www.incogent.io/eula"'));
assert.ok(eulaRendered.includes('href="mailto:legal@incogent.io"'));
